spring:
  application:
    name: 'profilematcher'

  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 300000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
